In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
heart_df = pd.read_csv('heart.csv')
heart_df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [5]:
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 86.2 KB

In [6]:
heart_df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [7]:
heart_df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

In [8]:
heart_df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [9]:
heart_df.duplicated().sum()

np.int64(0)

In [10]:
heart_df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [11]:
heart_df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='str')

In [12]:
cat_col = heart_df.select_dtypes(include='object').columns

In [13]:
for col in cat_col:
    print(col)
    print((heart_df[col].unique()),list(range(heart_df[col].nunique())))
    heart_df[col].replace(heart_df[col].unique(), range(heart_df[col].nunique()), inplace=True)
    print('*'*30)
    print()

Sex
<StringArray>
['M', 'F']
Length: 2, dtype: str [0, 1]
******************************

ChestPainType
<StringArray>
['ATA', 'NAP', 'ASY', 'TA']
Length: 4, dtype: str [0, 1, 2, 3]
******************************

RestingECG
<StringArray>
['Normal', 'ST', 'LVH']
Length: 3, dtype: str [0, 1, 2]
******************************

ExerciseAngina
<StringArray>
['N', 'Y']
Length: 2, dtype: str [0, 1]
******************************

ST_Slope
<StringArray>
['Up', 'Flat', 'Down']
Length: 3, dtype: str [0, 1, 2]
******************************

In [14]:
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [15]:
heart_df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
223     10
220     10
211      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

In [16]:
heart_df['Cholesterol'].replace(0, np.nan, inplace=True)

0      289.0
1      180.0
2      283.0
3      214.0
4      195.0
       ...
913    264.0
914    193.0
915    131.0
916    236.0
917    175.0
Name: Cholesterol, Length: 918, dtype: float64

In [17]:
# Ensure all features are numeric before KNN imputation
obj_cols = heart_df.select_dtypes(include="object").columns
if len(obj_cols) > 0:
    heart_df[obj_cols] = heart_df[obj_cols].apply(lambda s: pd.factorize(s)[0])

In [18]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute, columns=heart_df.columns)

In [19]:
heart_df['Cholesterol'].isna().sum()

np.int64(0)

In [20]:
count = 0
for i in heart_df['Cholesterol']:
    if i ==0:
        count +=1
    print(count)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
123
123
123
123
123
124
124
125
126
126
126
127
128
129
130
130
130
130
131
132
133
134
135
136
137
138
139
139
139
139
140
140
140
141
142
143
143
144
144
145
146
147
148
149
149
150
150
151
152
152
153
154
154
154
155
156
157
157
158
159
159
160
160
161
162
163
163
164
165
165
165
165
165
165
165
165
166
166
166
166
166
166
166
166
166
166
166
166
166
166
166
166
167
167
167
167
167
167
168
169
169
169
170
170
170
170
170
170
170
170
170
170
170
170
170
170
170
170
170
171
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172
172

In [21]:
heart_df['RestingBP'][heart_df['RestingBP']==0]

449    0.0
Name: RestingBP, dtype: float64

In [22]:
from sklearn.impute import KNNImputer
heart_df['RestingBP'].replace(0, np.nan, inplace=True)
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute, columns=heart_df.columns)

In [23]:
heart_df['RestingBP'].unique()

array([140., 160., 130., 138., 150., 120., 110., 136., 115., 100., 124.,
       113., 125., 145., 112., 132., 118., 170., 142., 190., 135., 180.,
       108., 155., 128., 106.,  92., 200., 122.,  98., 105., 133.,  95.,
        80., 137., 185., 165., 126., 152., 116.,   0., 144., 154., 134.,
       104., 139., 131., 141., 178., 146., 158., 123., 102.,  96., 143.,
       172., 156., 114., 127., 101., 174.,  94., 148., 117., 192., 129.,
       164.])

In [24]:
heart_df['RestingBP'].isnull().sum()

np.int64(0)

In [25]:
withoutOldPeak = heart_df.columns
withoutOldPeak = withoutOldPeak.drop('Oldpeak')
heart_df[withoutOldPeak] = heart_df[withoutOldPeak].astype('int32')

In [26]:
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int32
 1   Sex             918 non-null    int32
 2   ChestPainType   918 non-null    int32
 3   RestingBP       918 non-null    int32
 4   Cholesterol     918 non-null    int32
 5   FastingBS       918 non-null    int32
 6   RestingECG      918 non-null    int32
 7   MaxHR           918 non-null    int32
 8   ExerciseAngina  918 non-null    int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int32
 11  HeartDisease    918 non-null    int32
dtypes: float64(1), int32(11)
memory usage: 46.7 KB

Data Visualization

In [27]:
import plotly.express as px

In [28]:
heart_df.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
648,59,0,2,170,326,0,2,140,1,3.4,2,1

In [29]:
heart_df.corr()['HeartDisease'][:-1]

Age               0.282039
Sex              -0.305445
ChestPainType     0.459017
RestingBP         0.107589
Cholesterol      -0.232741
FastingBS         0.267291
RestingECG        0.061011
MaxHR            -0.400421
ExerciseAngina    0.494282
Oldpeak           0.403951
ST_Slope          0.558771
Name: HeartDisease, dtype: float64

In [30]:
px.line(heart_df.corr()['HeartDisease'][:-1].sort_values())

In [31]:
px.sunburst(heart_df,path=['HeartDisease','Age'])

In [32]:
px.histogram(heart_df, x='Age',color='HeartDisease')

In [33]:
px.pie(heart_df, names='HeartDisease', title='Percentage of HeartDisease classes distribution')

In [34]:
px.histogram(heart_df, x='Sex', color='HeartDisease')

In [35]:
px.histogram(heart_df,x='ChestPainType', color='HeartDisease')

In [36]:
heart_df['RestingBP'].unique()

array([140, 160, 130, 138, 150, 120, 110, 136, 115, 100, 124, 113, 125,
       145, 112, 132, 118, 170, 142, 190, 135, 180, 108, 155, 128, 106,
        92, 200, 122,  98, 105, 133,  95,  80, 137, 185, 165, 126, 152,
       116,   0, 144, 154, 134, 104, 139, 131, 141, 178, 146, 158, 123,
       102,  96, 143, 172, 156, 114, 127, 101, 174,  94, 148, 117, 192,
       129, 164], dtype=int32)

In [37]:
px.sunburst(heart_df, path=['HeartDisease','RestingBP'])

In [38]:
px.histogram(heart_df,x='FastingBS',color='HeartDisease')

In [39]:
px.sunburst(heart_df, path=['HeartDisease','MaxHR'])

In [40]:
px.violin(heart_df,x='HeartDisease',y='MaxHR',color='HeartDisease')

In [41]:
px.violin(heart_df,x='HeartDisease',y='Oldpeak',color='HeartDisease')

In [42]:
px.histogram(heart_df,x='ST_Slope',color='HeartDisease')

In [43]:
px.histogram(heart_df,x='ExerciseAngina',color='HeartDisease')

Model Training

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    heart_df.drop('HeartDisease',axis=1),
    heart_df['HeartDisease'],
    test_size=0.2,
    random_state=42,
    stratify=heart_df['HeartDisease']
)

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

solver = ['lbfgs','liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
best_solver = ''
test_score = np.zeros(6)
for i,n in enumerate(solver):
    lr = LogisticRegression(solver=n).fit(x_train, y_train)
    test_score[i] = lr.score(x_test,y_test)
    if lr.score(x_test,y_test) == test_score.max():
        best_solver=n

print(best_solver)
lr = LogisticRegression(solver=best_solver)
lr.fit(x_train, y_train)
lr_pred = lr.predict(x_test)
print(f'LogisticRegression Score: {accuracy_score(y_test,lr_pred)}')

newton-cholesky
LogisticRegression Score: 0.8695652173913043

In [46]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score

kernels = {'linear':0, 'poly':0, 'rbf':0, 'sigmoid':0}
best=''
for i in kernels:
    svm=SVC(kernel=i)
    svm.fit(x_train, y_train)
    yhat = svm.predict(x_test)
    kernels[i]=f1_score(y_test,yhat,average='weighted')
    if kernels[i] == max(kernels.values()):
        best=i

svm=SVC(kernel=best)
svm.fit(x_train, y_train)
svm_pred = svm.predict(x_test)
print(f'SVM f1_score kernel({best}): {f1_score(y_test,svm_pred,average='weighted')}')

SVM f1_score kernel(linear): 0.8633552559911067

In [47]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dtree=DecisionTreeClassifier(class_weight='balanced')
param_grid={
    'max_depth': [3,4,5,6,7,8],
    'min_samples_split': [2,3,4],
    'min_samples_leaf': [1,2,3,4],
    'random_state': [0,42]
}

grid_search = GridSearchCV(dtree, param_grid, cv=5)
grid_search.fit(x_train,y_train)
Ctree = DecisionTreeClassifier(**grid_search.best_params_, class_weight='balanced')
Ctree.fit(x_train,y_train)
dtc_pred = Ctree.predict(x_test)
print("DecisionTree's Accuracy: ",accuracy_score(y_test,dtc_pred))

DecisionTree's Accuracy:  0.8641304347826086

In [48]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rfc=RandomForestClassifier()
param_grid={
    'n_estimators': [50,100,150,500],
    'max_features': ['sqrt','log2',None],
    'max_depth': [3,6,9,19],
    'max_leaf_nodes': [3,6,9]
}

grid_search = GridSearchCV(rfc, param_grid)
grid_search.fit(x_train,y_train)
rfctree = RandomForestClassifier(**grid_search.best_params_)
rfctree.fit(x_train,y_train)
rfc_pred = rfctree.predict(x_test)
print("RandomForestClassifier's Accuracy: ",accuracy_score(y_test,rfc_pred))

RandomForestClassifier's Accuracy:  0.875

In [53]:
import pickle
file = open('heart_disease_predictor_LogisticRegression.pkl', 'wb')
pickle.dump(lr, file)

In [50]:
file1 = open('heart_disease_predictor_SVM.pkl', 'wb')
pickle.dump(svm, file1)

In [54]:
file2 = open('heart_disease_predictor_DecisionTree.pkl', 'wb')
pickle.dump(Ctree, file2)

In [52]:
file3 = open('heart_disease_predictor_RandomForest.pkl', 'wb')
pickle.dump(rfctree, file3)